# Generated by Django 2.1.2 on 2018-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sensors_data_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors_data',
            name='IMU',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensors_data',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensors_data',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensors_data',
            name='temp',
            field=models.FloatField(),
        ),
    ]
