# Generated by Django 2.1.2 on 2018-11-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181125_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors_Data',
            new_name='SensorsData',
        ),
    ]
