# Generated by Django 2.1.2 on 2018-11-26 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181125_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
