# Generated by Django 2.1.2 on 2018-11-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sensorsdata_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorsdata',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='sensorsdata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
